[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
onlyIncludeFiles = [
  "pnpm-lock.yaml",
  "pnpm-workspace.yaml",
  "package.json",
  "artifacts/api-client-react/package.json",
  "artifacts/api-server/package.json"
]
cmds = ["pnpm install --frozen-lockfile --prefer-offline"]

[phases.build]
cmds = ["pnpm turbo run build"]

[cache]
paths = [".pnpm-store", ".turbo"]

[start]
cmd = "pnpm --filter api-server start"
