import { Router, type IRouter } from "express";
import healthRouter from "./health";
import productsRouter from "./products";
import servicesRouter from "./services";
import bookingsRouter from "./bookings";
import reviewsRouter from "./reviews";
import cartRouter from "./cart";
import luckyRouter from "./lucky";
import submissionsRouter from "./submissions";
import catalogRouter from "./catalog";
import instagramRouter from "./instagram";
import webhooksRouter from "./webhooks";
import manychatRouter from "./manychat";
import adminInboxRouter from "./admin-inbox";
import ordersRouter from "./orders";
import tryOnRouter from "./try-on";
import campaignsRouter from "./campaigns";
import adsRouter from "./ads";
import teamRouter from "./team";
import callsRouter from "./calls";
import appointmentsRouter from "./appointments";
import yaraCallRouter from "./yara-call";
import chatRouter from "./chat";
import automationRouter from "./automation";

const router: IRouter = Router();

router.use(healthRouter);
router.use(productsRouter);
router.use(servicesRouter);
router.use(bookingsRouter);
router.use(reviewsRouter);
router.use(cartRouter);
router.use(luckyRouter);
router.use(submissionsRouter);
router.use(catalogRouter);
router.use(instagramRouter);
router.use(webhooksRouter);
router.use(manychatRouter);
router.use(adminInboxRouter);
router.use(ordersRouter);
router.use(tryOnRouter);
router.use(campaignsRouter);
router.use(adsRouter);
router.use(teamRouter);
router.use(callsRouter);
router.use(appointmentsRouter);
router.use(yaraCallRouter);
router.use(chatRouter);
router.use(automationRouter);

export default router;
